sudo: required
services: 
  -docker

before-install:
  -docker build -t RajKannupaiyan/docker-react -f Dockerfile.dev .

script:
  - docker run RajKannupaiyan/docker-react npm run test -- -- coverage
  
