sudo: required
services: 
  -docker

before-install:
  -docker build -t RajKannupaiyan/docker-react -f Dockerfile.dev .

script:
  - docker run RajKannupaiyan/docker-react npm run test -- -- coverage

deploy: 
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 env: "docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-030537193844"
 bucket_path:  "docker"
  on:
     branch: master
access_key_id: $AWS_ACCESS_KEY
